### ISSUE TITLE
Code Study

### ISSUE THREAD

**Issue by Bob0123456** [llllssss94/Fuzzy_Protocol_Inference_Anomaly_Detection#1]
Where can I read your dissertation?

**Comment by llllssss94** [comment]
Hello.
Here's a link for dissertation.
[http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=8de97f86a90b2258ffe0bdc3ef48d419](http://www.riss.kr/search/detail/DetailView.do?p_mat_type=be54d9b8bc7cdb09&control_no=8de97f86a90b2258ffe0bdc3ef48d419)

Unfotunately, It doesn't have english ver.
Thanks
